version: '1'
services:
  inference-container:
    build:
      context: ./inference_container
    ports:
      - "7860:7860"
    volumes:
      - ../model:/workspace/model
      - ../data:/workspace/data
    networks:
      - mynetwork

networks:
  mynetwork: